name: Node CI

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        # Avoid node 16.9.0
        # @see https://github.com/nodejs/node/issues/40030
        node: [12, 14, 16.8]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Install, build, and test
        run: npm install
